### ISSUE TITLE
UR5 self tests fail

### ISSUE THREAD

**Issue by westinsykes** [uw-biorobotics/IKBT#28]
When I run the self test for the UR5, I get a math domain error on line 128 coming from the asin function.

**Comment by blake5634** [comment]
Hi - could you please send your setup and output?  Thanks.
BH

**Comment by westinsykes** [comment]
Sure, here is the python file it generated for UR5 and the text output from me generating it and trying to use it without changing anything. Additionally I have tried changning the px, py, and pz files in the self test without any changes in the output. Let me know if I can get you any more info.

[IK_equationsUR5.py.txt](https://github.com/uw-biorobotics/IKBT/files/3725346/IK_equationsUR5.py.txt)
[IKoutput.txt](https://github.com/uw-biorobotics/IKBT/files/3725347/IKoutput.txt)


Thanks,

Westin

**Comment by blake5634** [comment]
I did a little experimentation.    The default pose for testing IK (Px = .2, Py=.4,Pz=.6 meters) turns out to be unreachable for UR5.   The generated python code right now does not include checks for this but you can add pretty easily.  Up on line 50 where it says

`solvable_pose = True`

write some code that checks for proper arguments to the asine equations below.   If they are outside the range -1 -- +1, then set solvable_pose to False. 

Yes - in the future we can automatically generated this checking code. 
BH

**Comment by westinsykes** [comment]
Thanks, Blake. This is a really cool project.
